Add Eth1 address withdrawal support
ethereum/eth2.0-deposit-cli pull request #195
Opened 2021-03-25 15:24 UTC by hwwhww

Fix #188, support https://github.com/ethereum/eth2.0-specs/pull/2149

- cli interface: add `--eth1_withdrawal_address` argument: If this field is set and valid, the given Eth1 address will be used to create the withdrawal credentials. Otherwise, it will generate withdrawal credentials with the mnemonic-derived withdrawal public key.
- `validate_deposit`: add public key and withdrawal credentials validations.

2021-03-25 15:35 UTC, hwwhww commented on eth2deposit/cli/generate_keys.py
> +    if not is_hex_address(address):
Note: the prefix `0x` is optional here.

2021-03-25 15:37 UTC, hwwhww commented
/cc @djrtwo 
Considering your de-Eth1/Eth2 rebranding, any plan to rename `ETH1_ADDRESS_WITHDRAWAL_PREFIX`?

2021-03-30 10:48 UTC, CarlBeek requested changes
I like that this is being added. 👍 

One issue is that by adding this functionality to `generate_keys` it is automagically added to both the `new-mnemonic` and `existing-mnemonic` commands. The latter of which doesn't have tests and isn't mentioned in the `README`.

2021-03-30 10:48 UTC, CarlBeek commented on eth2deposit/credentials.py
> +            withdrawal_credentials += self.eth1_withdrawal_address
Is it worth adding a sanity check here to handle the (hopefully impossible case) of when `self.eth1_withdrawal_address == None`?

2021-03-30 10:48 UTC, CarlBeek commented on eth2deposit/utils/validation.py
> +    # Verify withdrawal credential
I appreciate the additional checks here. 👍

2021-03-30 12:18 UTC, CarlBeek approved these changes
LGTM! Let's get it merged.

2021-03-30 12:23 UTC, merged

2021-05-17 20:01 UTC, edmont87 commented on eth2deposit/cli/generate_keys.py
> +    if not is_hex_address(address):
hi

2021-05-17 20:01 UTC, edmont87 commented on eth2deposit/cli/generate_keys.py
> +    if not is_hex_address(address):
hello word

2022-01-06 16:37 UTC, G-11-P reviewed
commit and merge